#define CSHARP
#undef PYTHON
#undef JAVA


using System;

namespace Directive;

class ConditionalDirective
{
	public static void Main(string[] args)
	{
#if (CSHARP)
		Console.WriteLine("CSHARP is defined");
#endif

		/////////////////////////////////////////////////
#if TESTING
	Console.WriteLine("Currently Testing");
#elif TRAINING
	Console.WriteLine("Currently Training");
#endif
		/////////////////////////////////

#if TESTING
	Console.WriteLine("Currently Testing");
#elif TRAINING
	Console.WriteLine("Currently Training");
#else
		Console.WriteLine("Neither Testing nor Training");
#endif
		////////////////////////////////////////////

#if (CSHARP && PYTHON)
				Console.WriteLine("CSHARP and PYTHON are defined");
#elif (CSHARP && !PYTHON)
		Console.WriteLine("CSHARP is defined, PYTHON is undefined");
#elif (!CSHARP && PYTHON)
				Console.WriteLine("PYTHON is defined, CSHARP is undefined");
#else
				Console.WriteLine("CSHARP and PYTHON are undefined");
#endif

		////////////////////////////
#if (!JAVA)
#warning JAVA is undefined
#endif

		///////////////////////
#line 200 "AnotherProgram.cs"
#warning Actual Warning generated by Program.cs on line 10
		///////////////////////
#pragma warning disable
#warning This is a warning 1
#pragma warning restore
#warning This is a warning 2
	}
}